### ISSUE TITLE
Uniform usage of bold/italic tags

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/arc-rdm.org#29]
Replace all instances of non-markdown highlighgting (e.g. usage of quoates or double quotes) with _italic_ or **bold** tags. 

Makes most sense once main content is done

**Comment by Freymaurer** [comment]
I skipped through all files and `documentation-principle.md` was the only file still using `""`. Check if usage is fine or should be replaced!

**Comment by Freymaurer** [comment]
@kMutagene
