### ISSUE TITLE
replace 404 page

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-rdm.org#58]
The 404 page is currently the default one from DataPLANT and redirects (offers to go back to) nfdi4plants.org. 

https://arc-rdm.org/something

I'd suggest to
- either add a specific 404 redirecting to https://arc-rdm.org/
- or updating the one from DataPLANT offering to go to arc-rdm.org/ or nfdi4plants.org

**Comment by Freymaurer** [comment]
should be done! but need to check

**Comment by j-bauer** [comment]
I removed the proxy 404 handler so it shouldn't get intercepted anymore. Please test and confirm :)

**Comment by Freymaurer** [comment]
The current 404.html can be found under `arc-website/404.`, which might be the reason why it is not found currently. Will change as soon as i move all configs to the new website

**Comment by j-bauer** [comment]
FYI: I was seeing the 404 page of the app and not that of dataplant today, so it seems to work.

**Comment by Freymaurer** [comment]
Yes it does show. But it looks horrible on mobile. Will zave to update on monday

**Comment by Freymaurer** [comment]
Done!
