### ISSUE TITLE
Re-use GraphNavigation cards / add to other pages

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-rdm.org#63]
I like the GraphNavigation cards at the bottom of home. 
My understanding is that they guide me as a reader (researcher or researcher) through topics in a sensible way (nodes left-to-right). 

<img width="1294" alt="Screenshot 2024-09-20 at 14 04 42" src="https://github.com/user-attachments/assets/c047ce61-ba82-4751-a22e-e7b61408e9fa">

However, once I click any node and am redirected to the linked article, I don't see the guiding navigation again (unless I actively go back home). That's confusing and I think we should use the feature more, especially since the card can easily be updated if needed. 

Would it make sense and is it feasible to reuse the cards? 
- Maybe add them at the bottom of left or right sidebar? 
- Or add (smaller versions of) them to the top / bottom of every linked article; then highlighting the node of the article I'm currently reading?

**Comment by kMutagene** [comment]
on another note, i think for the lower graph, versioning should come after FDO, 
So it is FDO > Versioning > Validation > DataHUB > Toolstack

![image](https://github.com/user-attachments/assets/185e4632-6379-4d22-bbde-ec1987ed5f2b)

**Comment by Freymaurer** [comment]
What is the state on this? Would you want the exact graph below or at the top or simply a classic "read next", etc. button?

**Comment by Brilator** [comment]
I'd suggest exact graph on top with current article node highlighted would be ideal.

**Comment by Freymaurer** [comment]
Ahm sorry, not time to do this. Will close 😞
