### ISSUE TITLE
Wrong link to "Partners" in Navbar 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-rdm.org#66]
In production the Navbar item `Partners` links to https://arc-rdm.org/details/partners (without the final slash https://arc-rdm.org/details/partners/). In dev mode, the link works. 

- Navbar.astro: `INTERNAL_PARTNERS = BASE_PATH + "details/partners",`
- static.ts:   `{href: URLS.INTERNAL_PARTNERS, text: "Partners"},`

both look fine.

**Comment by Freymaurer** [comment]
So the partners link does not work for you? For me it does work in production

![image](https://github.com/user-attachments/assets/df0f132f-d840-48f4-8e85-cdc85a85d077)

**Comment by Brilator** [comment]
Huh, never mind. Apparently some cache issue. Works fine in Firefox and Safari in private mode.
