### ISSUE TITLE
Styling of different cross-link types (dictionary, cross-reference, etc.)

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arc-rdm.org#70]
The mix of highlighting (bold, italic) / dictionary terms / internal cross-references can lead to somewhat ugly styling. 
Maybe make all dictionary-links and cross-links bold by default and underline dictionary links in addition?
Or is it easily possible to inherit styling for dictionary tagged words (e.g. if text is bold)? 

![Screenshot 2024-09-23 at 12 44 45](https://github.com/user-attachments/assets/24b2ea59-2689-4db1-aed5-d667b23b0cef)

**Comment by Freymaurer** [comment]
I think in request of @kMutagene i changed the dictionary links to be not bold 😅

**Comment by kMutagene** [comment]
I think it is better that some bold text looks weird occasionally rather than many passages of normal text being 50/50 bold due to dictionary link highlighting, but i guess that's personal preference

**Comment by kMutagene** [comment]
Ideally, dictionary link highlighting respects original styling but i can see how that's hard to implement

**Comment by kMutagene** [comment]
> Ideally, dictionary link highlighting respects original styling but i can see how that's hard to implement

or maybe not if the link style just adds the underline (without any other styling) @Freymaurer ?

**Comment by Freymaurer** [comment]
> > Ideally, dictionary link highlighting respects original styling but i can see how that's hard to implement
> 
> or maybe not if the link style just adds the underline (without any other styling) @Freymaurer ?

Sorry didnt see, not sure what you mean 😅

**Comment by Freymaurer** [comment]
Will close for now
